float64 timestamp
float32 battery_voltage
bool arm

int32 imu_gyro_x
int32 imu_gyro_y
int32 imu_gyro_z

int32 imu_xacc
int32 imu_yacc
int32 imu_zacc


int32 imu_gyro_compass_x
int32 imu_gyro_compass_y
int32 imu_gyro_compass_z


float32 q1
float32 q2
float32 q3
float32 q4
float32 rollspeed
float32 pitchspeed
float32 yawspeed

float32 roll
float32 pitch
float32 yaw

float32 internal_pressure
float32 external_pressure
int32 heading

float32[8] thruster_pwms
